name: Push branch - Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches-ignore:
      - main

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If this push event is related to a PR, cancel the job
      # This is to prevent duplicate deployments, as the PR workflow will handle it
      - uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: PR
      - name: Exit here if this is a PR related event
        if: steps.PR.outputs.pr_found == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Ignoring PR related pushes. Cancelling job."
          gh run cancel ${{ github.run_id }}
          exit 0
      # Exit 0: Otherwise the job will be reported as failed.
      # The correct exit code would probably be 78, but it will be reported as failed as well.

      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          DEPLOYMENT_OUTPUT=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --yes)
          echo "deployment_output=$DEPLOYMENT_OUTPUT" >> $GITHUB_OUTPUT
