name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          DEPLOYMENT_OUTPUT=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --yes)
          echo "deployment_output=$DEPLOYMENT_OUTPUT" >> $GITHUB_OUTPUT
      - name: test output
        run: echo ${{ steps.deploy.outputs.deployment_output }}
      - name: Post Deployment URL to PR
        if: success()
        uses: actions/github-script@v4
        with:
          script: |
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const prNumber = context.payload.pull_request.number;
            const deploymentOutput = '${{ steps.deploy.outputs.deployment_output }}';
            github.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: `The deployment is complete! You can view the preview here: ${deploymentOutput}`
            });
